language: node_js
node_js:
  - 9
install:
- yarn
cache: 
  directories:
  - "node_modules"
services: 
  - postgresql
postgres:
  adapter: postgresql
  database: koa_base
  username: postgres
before_script:
  - "psql -c 'create database koa_base;' -U postgres"
  - "yarn add sequelize-cli"
  - "cd api/db"
  - "sequelize db:migrate"
