language: node_js
node_js:
  - 9
postgres:
  adapter: postgresql
  database: koa_base
  username: postgres
before_script:
  - "psql -c 'create database koa_base;' -U postgres"
  - "sequelize db:migrate"
