language: node_js
node_js:
  - 9
cache:
  yarn: true
  directories:
    - node_modules
services: 
  - postgresql
postgres:
  adapter: postgresql
  database: koa_base
  username: postgres
before_script:
  - "psql -c 'create database koa_base;' -U postgres"
  - "yarn global add sequelize-cli"
  - "cd api/db"
  - "sequelize db:migrate"
env:
  - DATABASE_URL=postgres://postgres@localhost:5432/koa_base
  - NODE_ENV=test
  - DEBUG=app:*
  - SESSION_SECRET=super-secret-key